# Run this file

from lxml import etree

tree = etree.parse( "demo-1.xml" )
root = tree.getroot()

for sentence in root:
    print type(sentence.text) # print the text generated by lxml

# lxml provides Unicode string for you 
